#!/bin/bash
# Generate Traefik dynamic configuration based on PBS nodes
# Usage: ./generate_traefik_config.sh <output_file>

set -e

OUTPUT_FILE="${1:-/tmp/traefik_dynamic.yaml}"

# Get all unique hosts
if [ -n "$PBS_NODEFILE" ]; then
    sort -u "$PBS_NODEFILE" > /tmp/hosts.txt
else
    echo "ERROR: PBS_NODEFILE not set. Run this inside a PBS job."
    exit 1
fi

mapfile -t HOSTS < /tmp/hosts.txt
NUM_HOSTS=${#HOSTS[@]}

echo "Generating dynamic config for $NUM_HOSTS hosts..."

# Start YAML
cat > "$OUTPUT_FILE" << 'HEADER'
# Traefik Dynamic Configuration
# Auto-generated by generate_traefik_config.sh

http:
  routers:
    vllm-router:
      rule: "PathPrefix(`/`)"
      service: vllm-backends
      entryPoints:
        - web

  services:
    vllm-backends:
      loadBalancer:
        healthCheck:
          path: /health
          interval: 5s
          timeout: 3s
        servers:
HEADER

# Add all backends (6 per host, ports 8001-8006)
for host in "${HOSTS[@]}"; do
    for port in {8001..8006}; do
        echo "          - url: \"http://${host}:${port}\"" >> "$OUTPUT_FILE"
    done
done

echo "Generated $OUTPUT_FILE with $((NUM_HOSTS * 6)) backends"
cat "$OUTPUT_FILE"
